### PR TITLE
Allow delete when acknowledge

### PR DESCRIPTION
**Pull request by nicoalonso**
### Implementation

An option is added to delete the message when it was acknowledge.

### CODE REVIEW

**Comment by tamimaj** [comment]
@nicoalonso why you closed it?

**Comment by tamimaj** [comment]
> Because, I try to create a package in NPM.js Create a new pull request

The delete option is good. We can have it here. Why do you need a separate package? More things you want to customize?

**Comment by nicoalonso** [comment]
No, I don't need a separate package.

Now, I'm working in project and I need this option enable.

I didn't know how long it would take you to merge it

**Comment by tamimaj** [comment]
@nicoalonso I won't take long. Don't worry

**Pull request closed without merging**
