### PR TITLE
bug-1: strip the prefix prior to binding listeners if using keyPrefix.

### PR DESCRIPTION
**Pull request by zeejers**
Reasoning: 

When using a keyPrefix, it seems reasonable to define the @RedisStreamHandler() using the key without the prefix in front, for example
`@RedisStreamHandler(the:key)`
instead of 
`@RedisStreamHandler(some:prefix:the:key)`

So, the key that is stored for the handler in streamHandlerMap will end up being `the:key`

When you XADD to `some:prefix:the:key`, the lib will be calling `xreadgroup`, and the ioredis lib will AUTOMATICALLY prefix `some:prefix` to whatever stream key is specified.

Because the `notifyHandlers` method's stream input is based on the result of a redis.xreadgroup, the stream value ends up being the version of the key that contains the key prefix.  The lib attempts to look up the key WITH the prefix in the streamHandlerMap, and doesn't find a matching key, because the version contained in streamHandlerMap is the version WITHOUT the prefix. Thus, when handler is called, its undefined.

The reasoning here is that if we ever end up with a stream name when calling the low level .xreadgroup command that starts with the keyPrefix, and the redis client keyPrefix is populated, then we KNOW it should be stripped, because if you're using a keyPrefix you don't include the keyPrefix in the key you are specifying, only on the actual redis client configuration.

### CODE REVIEW

**Comment by tamimaj** [comment]
@zeejers Thanks for the efforts and is a start. 
However, the problem is not solved. The lib when starts will create consumer groups for all streams. If we have the prefix, the stream will be "prefix:streamNameFromHandler", if we don't, is only "streamNameFromHandler". 
The lib creates consumer groups for all the streams in handler when starts, before listening. 

The logic of creating consumer group, needs to be changed, we have to see if we have a prefix, then we need to create consumer groups for streams with the prefix, otherwise listening will fail anyway.

Check error in screenshot. Also, check how IO Redis lib is prefixing the prefix without colon, which is what I told in the other messages.
image


Removing the prefix from the handler was not a problem, we can not pass it directly, and done. 

The problems is:
Consumer group creation logic needs to be changed in server side, and in client side as well, which has a listener for messages waiting responses.

**Comment by zeejers** [comment]
Hey @tamimaj  

The ioredis keyPrefix setting is not intended to auto-add a colon. It adds whatever prefix you specify, without additional logic. Adding some extra behavior to auto-add the colon in nestjs-redis-streams is something you **could do** but it would not be in line with the default ioredis behavior around that property, right?

> The lib creates consumer groups for all the streams in handler when starts, before listening.

Yes, and I noticed that it creates those consumer groups based on the listeners you've defined by decorating controller methods. When you create a consumer group using this command
```typescripts
await this.redis.xgroup('CREATE', stream, consumerGroup, '$', 'MKSTREAM');
```
The delegated call to this.redis.xgroup will AUTOMATICALLY prepend whatever prefix you've specified (because the redis client automatically handles it if you're using a keyPrefix...). 

And because of this, it seems like it would make sense to define your stream handler without a prefix, like this
```ts
@RedisStreamHandler('streamNameWithoutPrefix')
```

At this point, when xread is called with `streamNameWithoutPrefix` the call to xreadgroup will return stream names **WITH THE PREFIX INCLUDED**, because again, the redis client will automatically handle keyPrefixes behind the scenes.

This code change does not strip the prefix from the handler, but the return results that come back from xreadgroup when its passed into `notifyHandlers`, because the keyPrefix that wasn't there on the input is automagically prepended when the results come back from the xreadgroup call. See existing code:

```
 results = await this.redis.xreadgroup(
  // ...
  );

  for (let result of results) {
    let [stream, messages] = result;
    await this.notifyHandlers(stream, messages);
  }
```

You're using the direct result from the redis client which automagically includes the keyPrefix in the response stream names, and so when passing it into notifyHandlers there is not a matching streamHandlerMap property. 

Hopefully this makes sense.

Anyways, it seems like it could be approached in a few different ways, but this is the method that worked to solve the problem for us and our needs.

**Comment by tamimaj** [comment]
@zeejers Sorry for late response, I got a bit busy.

>The ioredis keyPrefix setting is not intended to auto-add a colon. It adds whatever prefix you specify, without additional logic. Adding some extra behavior to auto-add the colon in nestjs-redis-streams is something you could do but it would not be in line with the default ioredis behavior around that property, right?

I thought is the behaviour from your previous code you provided in the bug report. My bad. Yeah, we keep it as ioredis standard.

> The delegated call to this.redis.xgroup will AUTOMATICALLY prepend whatever prefix you've specified (because the redis client automatically handles it if you're using a keyPrefix...).

This part is not working for me, the streams are not created with the prefix nor the consumer groups for these streams, as it should be. If the streams are there and the consumer groups are there, all works, but the automatic creation is failing if stream is not in the redis instance.

Try delete yours locally and run the lib, and see if you get similar error of what I provided earlier in the screenshot.

**Comment by zeejers** [comment]
Hey @tamimaj - 

I reviewed and did indeed experience the issue you ran into. I updated the PR, please take a look. It looks like ioredis xgroup has an oddity that prevents keyPrefix from automatically being prepended... https://github.com/redis/ioredis/issues/1659

To account for this I'm manually prepending the keyPrefix in the createConsumerGroup, and then stripping the prefix within notifyHandlers.

This worked to solve the problem for us, but again, feel free to take the learnings here and adapt to the needs of your own patterns in the lib.

**Pull request merged**
